Traceback (most recent call last):
  File "/usr/share/miniconda3/envs/obsastro/lib/python3.8/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/usr/share/miniconda3/envs/obsastro/lib/python3.8/site-packages/nbclient/client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/usr/share/miniconda3/envs/obsastro/lib/python3.8/site-packages/jupyter_core/utils/__init__.py", line 166, in wrapped
    return loop.run_until_complete(inner)
  File "/usr/share/miniconda3/envs/obsastro/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/usr/share/miniconda3/envs/obsastro/lib/python3.8/site-packages/nbclient/client.py", line 705, in async_execute
    await self.async_execute_cell(
  File "/usr/share/miniconda3/envs/obsastro/lib/python3.8/site-packages/nbclient/client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/usr/share/miniconda3/envs/obsastro/lib/python3.8/site-packages/nbclient/client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
sky_level = 20
sky_only = sky_background(synthetic_image, sky_level)
show_image(sky_only, cmap='gray')
plt.title('Sky background only, {} counts input'.format(sky_level), fontsize=20)
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mNameError[0m                                 Traceback (most recent call last)
Cell [0;32mIn[12], line 2[0m
[1;32m      1[0m sky_level [38;5;241m=[39m [38;5;241m20[39m
[0;32m----> 2[0m sky_only [38;5;241m=[39m [43msky_background[49m[43m([49m[43msynthetic_image[49m[43m,[49m[43m [49m[43msky_level[49m[43m)[49m
[1;32m      3[0m show_image(sky_only, cmap[38;5;241m=[39m[38;5;124m'[39m[38;5;124mgray[39m[38;5;124m'[39m)
[1;32m      4[0m plt[38;5;241m.[39mtitle([38;5;124m'[39m[38;5;124mSky background only, [39m[38;5;132;01m{}[39;00m[38;5;124m counts input[39m[38;5;124m'[39m[38;5;241m.[39mformat(sky_level), fontsize[38;5;241m=[39m[38;5;241m20[39m)

Cell [0;32mIn[11], line 17[0m, in [0;36msky_background[0;34m(image, sky_counts, gain)[0m
[1;32m      1[0m [38;5;28;01mdef[39;00m [38;5;21msky_background[39m(image, sky_counts, gain[38;5;241m=[39m[38;5;241m1[39m):
[1;32m      2[0m [38;5;250m    [39m[38;5;124;03m"""[39;00m
[1;32m      3[0m [38;5;124;03m    Generate sky background, optionally including a gradient across the image (because[39;00m
[1;32m      4[0m [38;5;124;03m    some times Moons happen).[39;00m
[0;32m   (...)[0m
[1;32m     15[0m [38;5;124;03m        Gain of the camera, in units of electrons/ADU.[39;00m
[1;32m     16[0m [38;5;124;03m    """[39;00m
[0;32m---> 17[0m     sky_im [38;5;241m=[39m [43mnoise_rng[49m[38;5;241m.[39mpoisson(sky_counts [38;5;241m*[39m gain, size[38;5;241m=[39mimage[38;5;241m.[39mshape) [38;5;241m/[39m gain
[1;32m     19[0m     [38;5;28;01mreturn[39;00m sky_im

[0;31mNameError[0m: name 'noise_rng' is not defined

