Traceback (most recent call last):
  File "/usr/share/miniconda3/envs/obsastro/lib/python3.8/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/usr/share/miniconda3/envs/obsastro/lib/python3.8/site-packages/nbclient/client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/usr/share/miniconda3/envs/obsastro/lib/python3.8/site-packages/jupyter_core/utils/__init__.py", line 166, in wrapped
    return loop.run_until_complete(inner)
  File "/usr/share/miniconda3/envs/obsastro/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/usr/share/miniconda3/envs/obsastro/lib/python3.8/site-packages/nbclient/client.py", line 705, in async_execute
    await self.async_execute_cell(
  File "/usr/share/miniconda3/envs/obsastro/lib/python3.8/site-packages/nbclient/client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/usr/share/miniconda3/envs/obsastro/lib/python3.8/site-packages/nbclient/client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
from astropy.table import Table
cat = Table.read('../_static/ObsAstroData/simulate_star_cat.fits')
cat[:5]
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mFileNotFoundError[0m                         Traceback (most recent call last)
Cell [0;32mIn[15], line 2[0m
[1;32m      1[0m [38;5;28;01mfrom[39;00m [38;5;21;01mastropy[39;00m[38;5;21;01m.[39;00m[38;5;21;01mtable[39;00m [38;5;28;01mimport[39;00m Table
[0;32m----> 2[0m cat [38;5;241m=[39m [43mTable[49m[38;5;241;43m.[39;49m[43mread[49m[43m([49m[38;5;124;43m'[39;49m[38;5;124;43m../_static/ObsAstroData/simulate_star_cat.fits[39;49m[38;5;124;43m'[39;49m[43m)[49m
[1;32m      3[0m cat[:[38;5;241m5[39m]

File [0;32m/usr/share/miniconda3/envs/obsastro/lib/python3.8/site-packages/astropy/table/connect.py:62[0m, in [0;36mTableRead.__call__[0;34m(self, *args, **kwargs)[0m
[1;32m     59[0m units [38;5;241m=[39m kwargs[38;5;241m.[39mpop([38;5;124m"[39m[38;5;124munits[39m[38;5;124m"[39m, [38;5;28;01mNone[39;00m)
[1;32m     60[0m descriptions [38;5;241m=[39m kwargs[38;5;241m.[39mpop([38;5;124m"[39m[38;5;124mdescriptions[39m[38;5;124m"[39m, [38;5;28;01mNone[39;00m)
[0;32m---> 62[0m out [38;5;241m=[39m [38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43mregistry[49m[38;5;241;43m.[39;49m[43mread[49m[43m([49m[38;5;28;43mcls[39;49m[43m,[49m[43m [49m[38;5;241;43m*[39;49m[43margs[49m[43m,[49m[43m [49m[38;5;241;43m*[39;49m[38;5;241;43m*[39;49m[43mkwargs[49m[43m)[49m
[1;32m     64[0m [38;5;66;03m# For some readers (e.g., ascii.ecsv), the returned `out` class is not[39;00m
[1;32m     65[0m [38;5;66;03m# guaranteed to be the same as the desired output `cls`.  If so,[39;00m
[1;32m     66[0m [38;5;66;03m# try coercing to desired class without copying (io.registry.read[39;00m
[1;32m     67[0m [38;5;66;03m# would normally do a copy).  The normal case here is swapping[39;00m
[1;32m     68[0m [38;5;66;03m# Table <=> QTable.[39;00m
[1;32m     69[0m [38;5;28;01mif[39;00m [38;5;28mcls[39m [38;5;129;01mis[39;00m [38;5;129;01mnot[39;00m out[38;5;241m.[39m[38;5;18m__class__[39m:

File [0;32m/usr/share/miniconda3/envs/obsastro/lib/python3.8/site-packages/astropy/io/registry/core.py:203[0m, in [0;36mUnifiedInputRegistry.read[0;34m(self, cls, format, cache, *args, **kwargs)[0m
[1;32m    199[0m [38;5;28;01mtry[39;00m:
[1;32m    200[0m     ctx [38;5;241m=[39m get_readable_fileobj(
[1;32m    201[0m         args[[38;5;241m0[39m], encoding[38;5;241m=[39m[38;5;124m"[39m[38;5;124mbinary[39m[38;5;124m"[39m, cache[38;5;241m=[39mcache
[1;32m    202[0m     )
[0;32m--> 203[0m     fileobj [38;5;241m=[39m [43mctx[49m[38;5;241;43m.[39;49m[38;5;21;43m__enter__[39;49m[43m([49m[43m)[49m
[1;32m    204[0m [38;5;28;01mexcept[39;00m [38;5;167;01mOSError[39;00m:
[1;32m    205[0m     [38;5;28;01mraise[39;00m

File [0;32m/usr/share/miniconda3/envs/obsastro/lib/python3.8/contextlib.py:113[0m, in [0;36m_GeneratorContextManager.__enter__[0;34m(self)[0m
[1;32m    111[0m [38;5;28;01mdel[39;00m [38;5;28mself[39m[38;5;241m.[39margs, [38;5;28mself[39m[38;5;241m.[39mkwds, [38;5;28mself[39m[38;5;241m.[39mfunc
[1;32m    112[0m [38;5;28;01mtry[39;00m:
[0;32m--> 113[0m     [38;5;28;01mreturn[39;00m [38;5;28;43mnext[39;49m[43m([49m[38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43mgen[49m[43m)[49m
[1;32m    114[0m [38;5;28;01mexcept[39;00m [38;5;167;01mStopIteration[39;00m:
[1;32m    115[0m     [38;5;28;01mraise[39;00m [38;5;167;01mRuntimeError[39;00m([38;5;124m"[39m[38;5;124mgenerator didn[39m[38;5;124m'[39m[38;5;124mt yield[39m[38;5;124m"[39m) [38;5;28;01mfrom[39;00m [38;5;28;01mNone[39;00m

File [0;32m/usr/share/miniconda3/envs/obsastro/lib/python3.8/site-packages/astropy/utils/data.py:353[0m, in [0;36mget_readable_fileobj[0;34m(name_or_obj, encoding, cache, show_progress, remote_timeout, sources, http_headers, use_fsspec, fsspec_kwargs, close_files)[0m
[1;32m    344[0m [38;5;28;01mif[39;00m is_url:
[1;32m    345[0m     name_or_obj [38;5;241m=[39m download_file(
[1;32m    346[0m         name_or_obj,
[1;32m    347[0m         cache[38;5;241m=[39mcache,
[0;32m   (...)[0m
[1;32m    351[0m         http_headers[38;5;241m=[39mhttp_headers,
[1;32m    352[0m     )
[0;32m--> 353[0m fileobj [38;5;241m=[39m [43mio[49m[38;5;241;43m.[39;49m[43mFileIO[49m[43m([49m[43mname_or_obj[49m[43m,[49m[43m [49m[38;5;124;43m"[39;49m[38;5;124;43mr[39;49m[38;5;124;43m"[39;49m[43m)[49m
[1;32m    354[0m [38;5;28;01mif[39;00m is_url [38;5;129;01mand[39;00m [38;5;129;01mnot[39;00m cache:
[1;32m    355[0m     delete_fds[38;5;241m.[39mappend(fileobj)

[0;31mFileNotFoundError[0m: [Errno 2] No such file or directory: '../_static/ObsAstroData/simulate_star_cat.fits'

