Traceback (most recent call last):
  File "/usr/share/miniconda3/envs/obsastro/lib/python3.8/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/usr/share/miniconda3/envs/obsastro/lib/python3.8/site-packages/nbclient/client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/usr/share/miniconda3/envs/obsastro/lib/python3.8/site-packages/jupyter_core/utils/__init__.py", line 166, in wrapped
    return loop.run_until_complete(inner)
  File "/usr/share/miniconda3/envs/obsastro/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/usr/share/miniconda3/envs/obsastro/lib/python3.8/site-packages/nbclient/client.py", line 705, in async_execute
    await self.async_execute_cell(
  File "/usr/share/miniconda3/envs/obsastro/lib/python3.8/site-packages/nbclient/client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/usr/share/miniconda3/envs/obsastro/lib/python3.8/site-packages/nbclient/client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
%matplotlib inline

from ipywidgets import interactive, interact

@interact(bias_level=(1000, 1200, 10), 
          dark=(0.01, 1, 0.01), 
          sky_counts_per_sec=(0, 3, 0.1),
          gain=(0.5, 3.0, 0.1), 
          read=(0, 50, 2.0),
          exposure=(100, 1200, 100),
          seeing=(0.5, 3, 0.5)
         )


def complete_image(bias_level=1100, read=10.0, gain=1, dark=0.1, 
                   exposure=300, sky_counts_per_sec=0.3, 
                   seeing=1.5):
    synthetic_image = np.zeros([500, 500])
    show_image(synthetic_image + 
               read_noise(synthetic_image, read, gain) +
               bias(synthetic_image, bias_level, realistic=True) + 
               dark_current(synthetic_image, dark, exposure, gain) +
               sky_background(synthetic_image, sky_counts_per_sec, exposure, gain) +
               inject_stars(synthetic_image, cat, w, exposure, gain, seeing),
               cmap='gray',
               figsize=(6, 6))
    
i = interactive(complete_image, 
                bias_level=(1000, 1200, 10), 
                dark=(0.01, 1, 0.01), 
                sky_counts_per_sec=(0, 3, 0.1),
                gain=(0.5, 3.0, 0.1), 
                read=(0, 50, 2.0),
                exposure=(100, 1200, 100),
                seeing=(0.5, 3, 0.5)
                )

for kid in i.children:
    try:
        kid.continuous_update = False
    except KeyError:
        pass
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mModuleNotFoundError[0m                       Traceback (most recent call last)
Cell [0;32mIn[24], line 3[0m
[1;32m      1[0m get_ipython()[38;5;241m.[39mrun_line_magic([38;5;124m'[39m[38;5;124mmatplotlib[39m[38;5;124m'[39m, [38;5;124m'[39m[38;5;124minline[39m[38;5;124m'[39m)
[0;32m----> 3[0m [38;5;28;01mfrom[39;00m [38;5;21;01mipywidgets[39;00m [38;5;28;01mimport[39;00m interactive, interact
[1;32m      5[0m [38;5;129m@interact[39m(bias_level[38;5;241m=[39m([38;5;241m1000[39m, [38;5;241m1200[39m, [38;5;241m10[39m), 
[1;32m      6[0m           dark[38;5;241m=[39m([38;5;241m0.01[39m, [38;5;241m1[39m, [38;5;241m0.01[39m), 
[1;32m      7[0m           sky_counts_per_sec[38;5;241m=[39m([38;5;241m0[39m, [38;5;241m3[39m, [38;5;241m0.1[39m),
[0;32m   (...)[0m
[1;32m     16[0m                    exposure[38;5;241m=[39m[38;5;241m300[39m, sky_counts_per_sec[38;5;241m=[39m[38;5;241m0.3[39m, 
[1;32m     17[0m                    seeing[38;5;241m=[39m[38;5;241m1.5[39m):
[1;32m     18[0m     synthetic_image [38;5;241m=[39m np[38;5;241m.[39mzeros([[38;5;241m500[39m, [38;5;241m500[39m])

[0;31mModuleNotFoundError[0m: No module named 'ipywidgets'

